apiVersion: apps/v1
kind: Deployment
metadata:
  name: downstream-springboot-deployment
  labels:
    app: downstream-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downstream-springboot
  template:
    metadata:
      labels:
        app: downstream-springboot
    spec:
      containers:
      - name: downstream-springboot
        image: tribikramsahoo/downstreamspringboot
        ports:
        - name: http
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: downstream-springboot-service
spec:
  selector:
    app: downstream-springboot
  ports:
    - protocol: TCP
      port: 8081
      targetPort: http
